// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tracker.api.data;

#nullable disable

namespace tracker.api.Migrations
{
    [DbContext(typeof(trackerDbContext))]
    [Migration("20231013182951_one")]
    partial class one
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tracker.api.Model.dailyTracker", b =>
                {
                    b.Property<int>("track_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("track_id"));

                    b.Property<string>("archv_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("end_dt")
                        .HasColumnType("datetime2");

                    b.Property<double>("hours")
                        .HasColumnType("float");

                    b.Property<DateTime>("last_modif")
                        .HasColumnType("datetime2");

                    b.Property<int>("product")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_dt")
                        .HasColumnType("datetime2");

                    b.Property<int>("work")
                        .HasColumnType("int");

                    b.HasKey("track_id");

                    b.ToTable("dailyTracker");

                    b.HasData(
                        new
                        {
                            track_id = 7001,
                            archv_flag = "N",
                            comments = "spent 2 days",
                            employee_id = "WRK-101",
                            hours = 18.0,
                            last_modif = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4594),
                            product = 1001,
                            start_dt = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4593),
                            work = 5001
                        },
                        new
                        {
                            track_id = 7002,
                            archv_flag = "N",
                            comments = "spent 2 days",
                            employee_id = "WRK-104",
                            hours = 18.0,
                            last_modif = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4600),
                            product = 1002,
                            start_dt = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4599),
                            work = 6001
                        },
                        new
                        {
                            track_id = 7003,
                            archv_flag = "N",
                            comments = "spent 2 days",
                            employee_id = "WRK-107",
                            hours = 18.0,
                            last_modif = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4603),
                            product = 1003,
                            start_dt = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4602),
                            work = 7001
                        });
                });

            modelBuilder.Entity("tracker.api.Model.domain.Department", b =>
                {
                    b.Property<int>("dept_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dept_id"));

                    b.Property<string>("archv_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dept_id");

                    b.ToTable("department");

                    b.HasData(
                        new
                        {
                            dept_id = 3001,
                            archv_flag = "N",
                            dept_name = "iseries"
                        },
                        new
                        {
                            dept_id = 3002,
                            archv_flag = "N",
                            dept_name = "Angular"
                        },
                        new
                        {
                            dept_id = 3003,
                            archv_flag = "N",
                            dept_name = "c#"
                        });
                });

            modelBuilder.Entity("tracker.api.Model.domain.Product", b =>
                {
                    b.Property<int>("prod_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prod_id"));

                    b.Property<int>("Department_id")
                        .HasColumnType("int");

                    b.Property<string>("archv_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("end_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("prod_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("prod_id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            prod_id = 1001,
                            Department_id = 3001,
                            archv_flag = "N",
                            end_dt = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4489),
                            prod_name = "NHL7",
                            start_dt = new DateTime(2009, 5, 8, 14, 40, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            prod_id = 1002,
                            Department_id = 3002,
                            archv_flag = "N",
                            prod_name = "Pas",
                            start_dt = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4493)
                        },
                        new
                        {
                            prod_id = 1003,
                            Department_id = 3003,
                            archv_flag = "N",
                            end_dt = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            prod_name = "Limbs",
                            start_dt = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4495)
                        });
                });

            modelBuilder.Entity("tracker.api.Model.domain.Work", b =>
                {
                    b.Property<int>("work_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("work_id"));

                    b.Property<int>("Department_id")
                        .HasColumnType("int");

                    b.Property<string>("archv_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("end_dt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("work_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("work_id");

                    b.HasIndex("Department_id");

                    b.ToTable("work");

                    b.HasData(
                        new
                        {
                            work_id = 5001,
                            Department_id = 3001,
                            archv_flag = "N",
                            end_dt = new DateTime(2023, 10, 13, 23, 59, 51, 177, DateTimeKind.Local).AddTicks(4433),
                            start_dt = new DateTime(2009, 5, 8, 14, 40, 52, 0, DateTimeKind.Unspecified),
                            work_name = "Coading"
                        });
                });

            modelBuilder.Entity("tracker.api.Model.domain.employee", b =>
                {
                    b.Property<string>("emp_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Department_id")
                        .HasColumnType("int");

                    b.Property<string>("admin")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("archv_flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("mail_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("master")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_id");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            emp_id = "WRK-101",
                            Department_id = 3001,
                            admin = "N",
                            archv_flag = "N",
                            mail_id = "wrk-101@dedalus.com",
                            master = "N",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-102",
                            Department_id = 3001,
                            admin = "Y",
                            archv_flag = "N",
                            mail_id = "wrk-102@dedalus.com",
                            master = "N",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-103",
                            Department_id = 3001,
                            admin = "Y",
                            archv_flag = "N",
                            mail_id = "wrk-103@dedalus.com",
                            master = "Y",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-104",
                            Department_id = 3002,
                            admin = "N",
                            archv_flag = "N",
                            mail_id = "wrk-104@dedalus.com",
                            master = "N",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-105",
                            Department_id = 3002,
                            admin = "Y",
                            archv_flag = "N",
                            mail_id = "wrk-105@dedalus.com",
                            master = "N",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-106",
                            Department_id = 3002,
                            admin = "Y",
                            archv_flag = "N",
                            mail_id = "wrk-106@dedalus.com",
                            master = "Y",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-107",
                            Department_id = 3003,
                            admin = "N",
                            archv_flag = "N",
                            mail_id = "wrk-107@dedalus.com",
                            master = "N",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-108",
                            Department_id = 3003,
                            admin = "Y",
                            archv_flag = "N",
                            mail_id = "wrk-108@dedalus.com",
                            master = "N",
                            password = "wrk"
                        },
                        new
                        {
                            emp_id = "WRK-109",
                            Department_id = 3003,
                            admin = "Y",
                            archv_flag = "N",
                            mail_id = "wrk-109@dedalus.com",
                            master = "Y",
                            password = "wrk"
                        });
                });

            modelBuilder.Entity("tracker.api.Model.domain.Work", b =>
                {
                    b.HasOne("tracker.api.Model.domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("Department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
